### ISSUE TITLE
Allow changing endpoint address

### ISSUE THREAD

**Issue by Clockwork-Muse** [Dancheg97/grpc-clicker#135]
![image](https://github.com/Dancheg97/grpclicker_vscode/assets/5569508/a4fb60f0-1fbb-4b9b-8957-42818519867d)

It's not possible to change the endpoint address.  Obviously the proto can be re-imported to change the address, but that would become annoying.  Allowing changing the address, or the ability to switch between set environments, would alleviate this.

**Comment by Dancheg97** [comment]
Yep, i had a version where that was possible, take a closer look to implement a bit later

**Comment by Dancheg97** [comment]
Implemented! :)

**Comment by Clockwork-Muse** [comment]
Thank you.
