### ISSUE TITLE
schema import path input is split into individual characters

### ISSUE THREAD

**Issue by LukeStorry** [Dancheg97/grpc-clicker#137]
The string provided to the `Import path` input box when ConnectionType is Proto file is split into individual characters and each is passed into the cli seperately.

<img width="815" alt="image" src="https://github.com/Dancheg97/grpc-clicker/assets/5787482/2e8b54c1-800d-4ca5-b42d-341679c37fd7">

**Comment by Dancheg97** [comment]
Done, reopen the issue if something is wrong.
